name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main    

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          cd years/2023/
          python -m pip install coverage
          coverage run --source=days/ --omit=days/__init__.py -m unittest discover -s tests -p 'test_*.py' 

      - name: Generate HTML coverage report
        run: |
          cd years/2023/
          coverage html
          coverage json
  
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Coverage report
          path: years/2023/htmlcov/

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-main@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./years/2023/htmlcov/
      - name: "Combine"
        run: |
          cd years/2023/
          coverage report | grep -E 'TOTAL' | awk '{print $NF}' | cut -d'%' -f1
          export TOTAL=$(coverage report | grep -E 'TOTAL' | awk '{print $NF}' | cut -d'%' -f1)
          echo "total=$TOTAL"
          echo "total=$TOTAL" >> $GITHUB_ENV
          echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY

      - name: "Make badge"
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          # GIST_TOKEN is a GitHub personal access token with scope "gist".
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 0ae8ce4137377b1d87a23e8590a7e726   # replace with your real Gist id.
          filename: years/2023/coverage.json
          label: Coverage
          message: ${{ env.total }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.total }}